# Generated by Django 5.1.4 on 2025-08-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('RES', 'Residential'), ('COM', 'Commercial'), ('IND', 'Industrial')], max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('square_feet', models.PositiveIntegerField()),
            ],
        ),
    ]
