# Generated by Django 5.1.4 on 2025-08-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='img', upload_to='project_image/'),
            preserve_default=False,
        ),
    ]
