# Generated by Django 5.1.4 on 2025-08-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='square_feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
