# Generated by Django 5.1.4 on 2025-08-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Residential property in kollam', max_length=250),
            preserve_default=False,
        ),
    ]
