# Generated by Django 5.1.4 on 2025-08-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feature1',
            field=models.CharField(default='Premium Quality Materials', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='feature2',
            field=models.CharField(default='Energy Efficient', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='feature3',
            field=models.CharField(default='Modern Design Concepts', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='feature4',
            field=models.CharField(default='Customizable Options', max_length=255),
        ),
    ]
