# Generated by Django 5.1.4 on 2025-08-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default='Residential', max_length=100),
            preserve_default=False,
        ),
    ]
