# Generated by Django 5.1.4 on 2025-09-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_images_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head_Carosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='carosel/')),
                ('image2', models.ImageField(upload_to='carosel/')),
            ],
        ),
    ]
