# Generated by Django 5.1.4 on 2025-09-10 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_head_carosel'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_carosel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
